<?php

namespace AssoMaker\PassSecuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassRepository extends EntityRepository
{
}
