<?php

namespace AssoMaker\AnimBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimationRepository extends EntityRepository
{
}
