<?php

namespace AssoMaker\AnimBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieMobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieMobileRepository extends EntityRepository
{
}
