<?php

namespace AssoMaker\AnimBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoAnimationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoAnimationRepository extends EntityRepository
{
}
