<?php

namespace AssoMaker\SponsoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvancementRepository extends EntityRepository
{
}
