parameters:
    database_driver:    "pdo_mysql"
    database_host:    "localhost"
    database_port:    ""
    database_name:    "phpm"
    database_user:    "phpm"
    database_password:    "5JxS65w7WwtQEVqv"
    mailer_transport:    "gmail"
    mailer_host:    ""
    mailer_user:    ""
    mailer_password:    ""
    locale:    "en"
    secret:    ""
    admin_email:    ""
    node_bin:    "/usr/bin/node"
    node_paths:    /usr/lib/node/
    
