<?php

namespace AssoMaker\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrationTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationTokenRepository extends EntityRepository
{
}
