PHPM\Bundle\Entity\PlageHoraire:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    debut:
      type: datetime
    fin:
      type: datetime
  lifecycleCallbacks: {  }
