PHPM\Bundle\Entity\Utilisateur:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    login:
      type: string
      length: 255
    pass:
      type: string
      length: 255
    email:
      type: string
      length: 255
  lifecycleCallbacks: {  }
