<?php

namespace AssoMaker\PHPMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BesoinMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinMaterielRepository extends EntityRepository
{
}