<?php

namespace AssoMaker\PHPMBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
	
	public function getPairsStartingBy($string)
	{
		
		 return $this->getEntityManager()
            ->createQuery("SELECT c FROM AssoMakerPHPMBundle:Config c WHERE c.field LIKE :string ")
		 	->setParameter('string', $string."%")
		 	->getResult();
	}
	
	public function findAllAsArray()
	{
	
	    $result = $this->getEntityManager()
	    ->createQuery("SELECT c.field, c.value FROM AssoMakerPHPMBundle:Config c ")->getArrayResult();
	    
	    $a = array();
	    foreach ($result as $row)
	    {
	        $a[$row['field']] = $row['value'];
	    }
	    return $a;
	        
	}
	
	
}