<?php

namespace AssoMaker\PHPMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielRepository extends EntityRepository
{
}