<?php

namespace AssoMaker\PHPMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlageHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlageHoraireRepository extends EntityRepository
{
// 	public function getConflictingPlages(\AssoMaker\BaseBundle\Entity\Orga $orga)
// 	{
// 		$orgaId = $orga->getId();
// 	var_dump($this->getEntityManager()
// 	->createQuery("SELECT ph,t,g FROM AssoMakerPHPMBundle:PlageHoraire ph JOIN ph.besoinsOrga bo JOIN bo.orgaHint o JOIN ph.tache t
// 			JOIN t.groupeTache g
// 			WHERE o.id = $orgaId AND t.statut >=0 AND ph.id NOT IN
// 			( SELECT ph1.id FROM AssoMakerPHPMBundle:PlageHoraire ph1 JOIN ph1.besoinsOrga bo1 JOIN bo1.orgaHint o1 JOIN ph1.tache t1
// 				WHERE (ph1.debut > ph.fin or ph1.fin < ph.debut) AND ph.id != ph1.id AND o1.id = $orgaId AND t1.statut >=0)
// 			ORDER BY ph.debut		")
// 			->getArrayResult());
	
// 	}
}