<?php

namespace PHPM\Bundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
	
	public function getPairsStartingBy($string)
	{
		
		 return $this->getEntityManager()
            ->createQuery("SELECT c FROM PHPMBundle:Config c WHERE c.field LIKE :string ")
		 	->setParameter('string', $string."%")
		 	->getResult();
	}
	
	
}