<?php

namespace PHPM\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DisponibiliteInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibiliteInscriptionRepository extends EntityRepository
{
    
    public function findAllWithOrgacount()
    {
    
        return $this->getEntityManager()
        ->createQuery("SELECT d, count(o) as nborga, o.permis FROM PHPMBundle:DisponibiliteInscription d JOIN d.orgas o GROUP BY d.id, o.permis")

        ->getArrayResult();
    
    
    }
}