<?php

namespace PHPM\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends EntityRepository
{
	public function findAllWithConfianceCode($code)
	{
	
		return  $this->createQueryBuilder('e')
		
		->join('e.confiance', 'c')
		->where('c.code = :code')
			  ->setParameter('code', $code);
				
	
	
	}
}