<?php

namespace PHPM\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimespanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimespanRepository extends EntityRepository
{
	public function getHours($id){
		$conn = $this->container->get('database_connection');
        $sql = '
SELECT t, max(orgas) FROM (
(
SELECT t, count(t2b) AS orgas FROM
((
SELECT t0.begintime AS t FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
)
UNION
(
SELECT t0.endtime  FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
) ) AS t1 , 

(SELECT t0.begintime AS t2b, t0.endtime AS t2e FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)) AS t2


WHERE (t>=t2b AND t<t2e)
GROUP BY t
)
UNION
 (
SELECT t, 0 FROM
((
SELECT t0.begintime AS t FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
)
UNION
(
SELECT t0.endtime  FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
) ) AS t1 , 

(SELECT t0.begintime AS t2b, t0.endtime AS t2e FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)) AS t2


WHERE NOT(t>=t2b AND t<t2e)
GROUP BY t
)

)AS t3 GROUP BY t';
        $rows = $conn->query($sql);
	
	
	
	
		return $ok;
	}
	
	
}