<?php

namespace PHPM\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeslotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeslotRepository extends EntityRepository
{
	
	public function getAffectable($id)
	{
		$em = $this->getEntityManager();
	
	
	
		$dql = "SELECT t FROM PHPMBundle:Timeslot t WHERE
	            t.id NOT IN 
	                (
	                SELECT t2.id FROM
	                PHPMBundle:Timeslot t1,
	                PHPMBundle:Timeslot t2
	                WHERE t1.orga =$id
	                AND (
	                NOT(t1.endtime <= t2.begintime OR t1.begintime >=t2.endtime)
	                OR t2.orga != 1 )
	                )
	            ";
	
	
		$query = $em->createQuery($dql);
	
		$entity = $query->getResult();
					
		return  $entity;
	}
	
	public function getAffectedAtTime($taskid,$time)
	{
		$em = $this->getEntityManager();
	
	
	
		$dql = "SELECT t FROM PHPMBundle:Timeslot t WHERE
		WHERE t.task =$id
		AND (
		NOT(t1.endtime <= t2.begintime OR t1.begintime >=t2.endtime)
		OR t2.orga != 1 )
		)
		";
	
	
		$query = $em->createQuery($dql);
	
		$entity = $query->getResult();
	
		return  $entity;
	}
	
	public function getFromTimespan($taskid,$timespanid)
	{
		$em = $this->getEntityManager();
	
	
	
		$dql = "SELECT t FROM PHPMBundle:Timeslot t , PHPMBundle:Timespan tsp
		WHERE tsp.id= $timespanid AND t.task = $taskid
		AND 
		(t.begintime <= tsp.endtime AND t.endtime >=tsp.begintime)
		
		";
	
	
		$query = $em->createQuery($dql);
	
		$entity = $query->getResult();
	
		return  $entity;
	}
	
	
	
	public function getHours(){
		
		
        $sql = '
SELECT t, max(orgas) FROM (
(
SELECT t, count(t2b) AS orgas FROM
((
SELECT t0.begintime AS t FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
)
UNION
(
SELECT t0.endtime  FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
) ) AS t1 , 

(SELECT t0.begintime AS t2b, t0.endtime AS t2e FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)) AS t2


WHERE (t>=t2b AND t<t2e)
GROUP BY t
)
UNION
 (
SELECT t, 0 FROM
((
SELECT t0.begintime AS t FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
)
UNION
(
SELECT t0.endtime  FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)
) ) AS t1 , 

(SELECT t0.begintime AS t2b, t0.endtime AS t2e FROM Timeslot t0, Timespan tsp WHERE t0.task_id=1 AND (t0.begintime <= tsp.endtime AND t0.endtime >= tsp.begintime)) AS t2


WHERE NOT(t>=t2b AND t<t2e)
GROUP BY t
)

)AS t3 GROUP BY t';
$rsm = new ResultSetMapping;
$rsm->addEntityResult('ts', 'u');
$rsm->addFieldResult('u', 'id', 'id');
$rsm->addFieldResult('u', 'name', 'name');

$query = $this->_em->createNativeQuery('SELECT id, name FROM users WHERE name = ?', $rsm);
$query->setParameter(1, 'romanb');

$users = $query->getResult();
		return $rows;
	}
	
	
}