<?php

namespace AssoMaker\ComptesPersoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemPreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPreferenceRepository extends EntityRepository
{
}
