<?php

namespace AssoMaker\ComptesPersoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StoreItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreItemRepository extends EntityRepository
{
}
