<?php

namespace AssoMaker\ComptesPersoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
	public function getOrgaBalance($orgaId){
		$entities = $this->getEntityManager()->getRepository('AssoMakerComptesPersoBundle:Transaction')->findByOrga($orgaId);

		if(!$entities){
			return 0;
		}else{
			$balance = 0;
			foreach ($entities as $transaction){
				$balance+=$transaction->getAmount();
			}
			return  $balance;

		}
	}	
}
